// Copies the Android GLSL ES 3.0 shaders into the website so the live
// previews run the exact shaders that ship in the library. WebGL2 speaks the
// same dialect, so the sources are used verbatim.
//
// Run `npm run shaders` after changing anything under
// android/src/main/assets/expo-gradients/shaders.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));
const source = path.resolve(root, "../../android/src/main/assets/expo-gradients/shaders");
const target = path.resolve(root, "../src/lib/engine/shaders/generated.ts");

function collect(directory) {
	return fs
		.readdirSync(directory, { withFileTypes: true })
		.flatMap((entry) => {
			const full = path.join(directory, entry.name);
			return entry.isDirectory() ? collect(full) : [full];
		})
		.filter((file) => /\.(glsl|vert|frag)$/.test(file))
		.sort();
}

const files = collect(source);
const entries = files.map((file) => {
	const key = path.relative(source, file).split(path.sep).join("/");
	return `\t${JSON.stringify(key)}: ${JSON.stringify(fs.readFileSync(file, "utf8"))},`;
});

const output = `// Generated by scripts/sync-shaders.mjs from android/src/main/assets. Do not edit.

export const shaderSources: Record<string, string> = {
${entries.join("\n")}
};
`;

fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, output);
console.log(`Synced ${files.length} shaders into ${path.relative(process.cwd(), target)}`);
